#!/bin/bash
thisdir="$(cd $(dirname $0) ; pwd -P)"
PATH="$thisdir:$PATH"
echo "Compactc version: $(exec "$thisdir/compactc.bin" --version)"
export COMPACT_PATH="$thisdir/lib/"
export ZKIR_PP="$thisdir"
exec "$thisdir/compactc.bin" $@
